version: "3"

services:
  api:
      #    build: .
    image: dexta423/serv-db-all:0.4
    command: npm start
    volumes:
     - ./:/var/www/
    ports:
      - "7423:8423"
    environment:
      NODE_ENV: dev
      BUILD_VERSION: 0.51
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: serviceuser
      MYSQL_PASSWORD: serviceuser23password
      MYSQL_DATABASE: serv
    depends_on:
      - sqldb
    networks:
      - frontendNetwork
      - backendNetwork

  sqldb:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: serviceuser
      MYSQL_PASSWORD: serviceuser23password
      MYSQL_DATABASE: serv
    networks:
      - backendNetwork
    volumes:
      - ./data/maria:/var/lib/mysql

networks:
  frontendNetwork:
  backendNetwork:
