DROP TABLE IF EXISTS `servtable`;
    
CREATE TABLE `servtable` (
  `key` VARCHAR(3072) NOT NULL DEFAULT 'NULL',
  `value` VARCHAR(3072) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`key`)
);

DROP TABLE IF EXISTS `usertoken`;
    
CREATE TABLE `usertoken` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `username` VARCHAR(64) NOT NULL DEFAULT 'NULL',
  `tokenstring` CHAR(64) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `history`;
    
CREATE TABLE `history` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `key` VARCHAR(3072) NOT NULL DEFAULT 'NULL',
  `value` VARCHAR(3072) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);
